"""Primary statistics of the paper with 20 K-session draws and 3 pre-training seeds. Writes results/draws20_primary.json.

Analysis rules.

R1  PRIMARY FAMILY (6 comparisons, A minus B):
      P1  encoder minus LightGBM            at K = 1 and K = 2 on GenAI and on CCMA   (4 comparisons)
      P2  encoder minus the same network without pre-training (scratch) at K = 1 and K = 2 on CCMA (2 comparisons)
    Everything else in this file is descriptive and outside the family.
R2  Metric: test macro-F1 (%) over the full test set of the split, over the classes present in truth or prediction
    (= sklearn f1_score(average='macro')); GenAI: 6 app x modality classes (y_joint), CCMA: 9 apps (y_app). Computed from
    results/runs/<run>/test_preds.npz (asserted aligned with the split's test indices and labels) and asserted equal to the
    macro_f1 of the last record of that run_id in results/locked_test_metrics.jsonl.
R3  Draws r = 0..19: configs/splits/{,ccma_}fewshot_k{K}_s{r}.json. Draws 0-4 are the five draws of the tables; 5-19 are
    generated by scripts/make_splits_draws20.py with exactly the same procedure (RandomState(1000+r) GenAI, RandomState(3000+r)
    CCMA), which reproduces the files of draws 0-4 exactly. Val and test sessions are identical in all 20 draws (asserted here).
R4  Pre-training seed p(r) = r mod 3. p = 0: weights/meta_ssl_mpm_XL.pt (the paper's encoder); p = 1, 2:
    weights/meta_ssl_mpm_XL_ps{p}.pt, same corpus (train+val sessions of both campaigns' standard session splits) and same
    recipe (src/pretrain_meta.py --datasets genai,ccma --d 192 --layers 8 --heads 8 --ff 384 --mask_ratio 0.4 --epochs 400
    --bs 256 --lr 0.001), only --seed differs. Asserted: identical n_flows and corpus statistics mu/sd in the three files.
R5  Observers per draw (fine-tune seed = r; the runs trained for the 20-draw design carry tag draws20). The encoder
    and scratch runs are produced by src/train_meta_ssl.py, the LightGBM runs by scripts/train_baselines.py:
    encoder  src/train_meta_ssl.py --init <weights of p(r)> --mode ft --epochs 60 --bs 64 --lr 0.001 --lr_enc 0.0003
             --drop_head 0.3 --first_k 64 --channels all, CKPT_SELECT=last (final epoch, no validation labels).
             r in {0, 3} (p = 0): the runs of the tables, [ccma_]fs{K}_sslXL_s{r}; every other r:
             [ccma_]fs{K}_sslXL_d{r}_p{p(r)}.
    scratch  the same with --init '' --arch 192,8,8,384 --norm_ckpt weights/meta_ssl_mpm_XL.pt (corpus standardisation,
             identical in the three pre-trainings by R4). r <= 4: the runs of the tables, [ccma_]fs{K}_sslscratchXL_s{r};
             else [ccma_]fs{K}_sslscratchXL_d{r}.
    LightGBM scripts/train_baselines.py --which lgbm, CKPT_SELECT=last, LGBM_ROUNDS=1600. r <= 4: the runs of the tables,
             [ccma_]fs{K}_lgbm_meta64_s{r}; else [ccma_]fs{K}_draws20_lgbm_meta64_s{r}.
    1-NN     input-space 1-NN, L1 distance, first 10 packets (scripts/trivial_baselines.feats_knn), recomputed here for every
             draw exactly as scripts/boot2.py does.
R6  Statistics per comparison:
    (a) point estimate: mean over the 20 draws of the per-draw difference A_r - B_r;
    (b) PRIMARY TEST: paired t over the 20 per-draw differences (df 19): two-sided p and 95% interval; Holm step-down over
        the 6 p-values of the family at family-wise alpha = 0.05. A difference is significant iff its Holm-adjusted p
        < 0.05; two observers are level iff the Holm-adjusted p >= 0.05 (a non-significance statement only; the interval
        is reported so its width is visible).
    (c) SENSITIVITY: two-level paired bootstrap scripts/boot2.Cell with R = 20 draws (B = 4000, RandomState(20260926); level 1
        the draws, level 2 whole test sessions), 95% percentile interval, two-sided bootstrap p = min(1, 2 min(P*(D <= 0),
        P*(D >= 0))), Holm-adjusted over the family in the same way. Reported next to (b).
    (d) Also reported: per-draw differences and the number of positive draws; per observer mean, SD, min and max over the
        20 draws; the mean difference within each pre-training seed (descriptive); the 5-draw reference = the paper's five
        draws (all p = 0: fs{K}_sslXL_s0-4 etc.) with the same t and boot2.Cell(R = 5) statistics (must reproduce
        results/boot2.json), and draws 0-4 of the 20-draw design.
    (e) Outside the family (descriptive, unadjusted p, labelled as such): encoder minus 1-NN at K = 1, 2 on both campaigns;
        the GenAI pre-training gain at K = 1, 2; the pre-training-seed effect on draws 1, 2, 4 (encoder with its p(r) weights
        minus the p = 0 encoder on the same draw).
"""
import collections, json, os, sys
import numpy as np
from scipy import stats

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, os.path.join(ROOT, 'src')); sys.path.insert(0, os.path.join(ROOT, 'scripts'))
R_ALL = 20
PSEED = lambda r: r % 3


def pre(ds): return '' if ds == 'genai' else 'ccma_'


def run_encoder(ds, K, r):
    return f'{pre(ds)}fs{K}_sslXL_s{r}' if r in (0, 3) else f'{pre(ds)}fs{K}_sslXL_d{r}_p{PSEED(r)}'


def run_scratch(ds, K, r):
    return f'{pre(ds)}fs{K}_sslscratchXL_s{r}' if r <= 4 else f'{pre(ds)}fs{K}_sslscratchXL_d{r}'


def run_lgbm(ds, K, r):
    return f'{pre(ds)}fs{K}_lgbm_meta64_s{r}' if r <= 4 else f'{pre(ds)}fs{K}_draws20_lgbm_meta64_s{r}'


def holm(p):
    p = np.asarray(p, float); m = len(p); o = np.argsort(p); adj = np.empty(m); run = 0.0
    for i, j in enumerate(o):
        run = max(run, min(1.0, (m - i) * p[j])); adj[j] = run
    return adj


def tstat(per):
    per = np.asarray(per, float); n = len(per); m = per.mean(); se = per.std(ddof=1) / np.sqrt(n)
    if se == 0: return dict(p=1.0 if m == 0 else 0.0, ci=[float(m), float(m)], se=0.0)
    tc = stats.t.ppf(0.975, n - 1)
    return dict(p=float(2 * stats.t.sf(abs(m / se), n - 1)), ci=[float(m - tc * se), float(m + tc * se)], se=float(se), df=n - 1)


def boot_compare(cell, a, b):
    c = cell.compare(a, b)
    d = cell.F[a]['boot'] - cell.F[b]['boot']; D = d[cell.Ss, np.arange(cell.B)[:, None]].mean(1)
    c['boot_p'] = float(min(1.0, 2 * min((D <= 0).mean(), (D >= 0).mean())))
    return c


def main():
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    import torch
    from data_mfr import GenAIData
    from trivial_baselines import feats_knn
    import boot2

    last = {}
    for line in open(os.path.join(ROOT, 'results', 'locked_test_metrics.jsonl'), encoding='utf-8'):
        try: rec = json.loads(line)
        except Exception: continue
        last[rec.get('run_id')] = rec

    # ---- R4: the three pre-trainings share corpus and recipe
    W = {0: 'weights/meta_ssl_mpm_XL.pt', 1: 'weights/meta_ssl_mpm_XL_ps1.pt', 2: 'weights/meta_ssl_mpm_XL_ps2.pt'}
    ck = {p: torch.load(os.path.join(ROOT, w), weights_only=False) for p, w in W.items()}
    keys = ('datasets', 'first_k', 'd', 'layers', 'heads', 'ff', 'mask_ratio', 'epochs', 'bs', 'lr')
    for p in (1, 2):
        assert all(ck[p]['args'][k] == ck[0]['args'][k] for k in keys), (p, ck[p]['args'])
        assert ck[p]['args']['seed'] == p and ck[p]['n_flows'] == ck[0]['n_flows']
        assert np.allclose(ck[p]['mu'], ck[0]['mu'], rtol=0, atol=1e-9) and np.allclose(ck[p]['sd'], ck[0]['sd'], rtol=0, atol=1e-9)
        assert ck[p]['args'].get('exclude', '') == '' and ck[p]['args'].get('target_frac', 1.0) == 1.0 and ck[p]['args'].get('steps_like', 0) == 0
    pre_info = {p: dict(file=W[p], seed=ck[p]['args']['seed'], n_flows=ck[p]['n_flows']) for p in W}

    def load(run, te, yte):
        z = np.load(os.path.join(ROOT, 'results', 'runs', run, 'test_preds.npz'))
        assert np.array_equal(z['idx'], te) and np.array_equal(z['y'], yte), run
        return z['pred']

    def f1_of(yte, p, NC):
        cm = np.zeros((NC, NC), np.int64); np.add.at(cm, (yte, p), 1); return 100 * boot2.macro_f1_cm(cm)

    OUT = dict(rules=__doc__, pretraining=pre_info, cells={}, family=[], outside_family=[], reference_5draw=[], checks={})
    fam_rows, out_rows = [], []
    for ds in ('genai', 'ccma'):
        D = GenAIData(ROOT, prefix=ds); ylab = D.y_joint if ds == 'genai' else D.y_app; NC = D.n_joint if ds == 'genai' else D.n_app
        Fk = feats_knn(D.meta, D.meta_len)
        for K in (1, 2):
            P = collections.defaultdict(list); te0 = None; runs = collections.defaultdict(list)
            for r in range(R_ALL):
                idx, _ = D.split_indices(os.path.join(ROOT, 'configs', 'splits', f'{pre(ds)}fewshot_k{K}_s{r}.json')); tr, te, va = idx['train'], idx['test'], idx['val']
                if te0 is None: te0, va0 = te, va
                assert np.array_equal(te0, te) and np.array_equal(va0, va), f'{ds} K={K} r={r}: val/test differ'
                yte = ylab[te]
                for name, fn in (('ours', run_encoder), ('scratch', run_scratch), ('lgbm', run_lgbm)):
                    rn = fn(ds, K, r); p = load(rn, te, yte); f = f1_of(yte, p, NC)
                    assert abs(f - 100 * last[rn]['test']['macro_f1']) < 1e-6, (rn, f, last[rn]['test']['macro_f1'])
                    P[name].append(p); runs[name].append(rn)
                p1 = np.empty(len(te), int)
                for b in range(0, len(te), 512): p1[b:b + 512] = ylab[tr][np.abs(Fk[te][b:b + 512, None, :] - Fk[tr][None]).sum(-1).argmin(1)]
                P['knn10'].append(p1); runs['knn10'].append('recomputed 1-NN (L1, first 10 packets)')
                if r <= 4:  # the paper's p=0 encoder on every one of the five draws
                    rn = f'{pre(ds)}fs{K}_sslXL_s{r}'; P['ours_p0'].append(load(rn, te, yte)); runs['ours_p0'].append(rn)
            y = ylab[te0]; sid = D.session_id[te0]
            cell = boot2.Cell(y, sid, NC, R=R_ALL)
            for a in ('ours', 'scratch', 'lgbm', 'knn10'): cell.add(a, P[a])
            obs = {a: dict(runs=runs[a], **cell.f1(a)) for a in ('ours', 'scratch', 'lgbm', 'knn10')}
            obs['ours']['pretraining_seed_per_draw'] = [PSEED(r) if r not in (0, 3) else 0 for r in range(R_ALL)]
            key = f'{ds}|K{K}'; OUT['cells'][key] = dict(n_test_sessions=int(cell.nS), n_test_connections=int(len(y)), observers=obs)

            def comp(a, b, family):
                c = boot_compare(cell, a, b); per = np.array(c['per_draw']); t = tstat(per)
                bys = {int(p): float(per[[i for i in range(R_ALL) if PSEED(i) == p]].mean()) for p in (0, 1, 2)}
                return dict(key=f'{key}|{a}-{b}', dataset=ds, K=K, A=a, B=b, family=family, diff=c['diff'], per_draw=c['per_draw'],
                            n_pos=c['n_pos'], n_neg=c['n_neg'], sd_draws=float(per.std(ddof=1)), t=t,
                            boot=dict(ci=c['ci'], p=c['boot_p'], n_resamples=c['n_resamples']), session_only=c['session_only'],
                            mean_by_pretraining_seed=bys, n_test_sessions=c['n_test_sessions'])
            fam_rows.append(comp('ours', 'lgbm', 'P1'))
            if ds == 'ccma': fam_rows.append(comp('ours', 'scratch', 'P2'))
            out_rows.append(comp('ours', 'knn10', 'outside'))
            if ds == 'genai': out_rows.append(comp('ours', 'scratch', 'outside'))
            # pre-training-seed effect on draws 1, 2, 4 (same draw, same fine-tune seed; p(r) weights minus p=0 weights)
            eff = [dict(draw=r, pseed=PSEED(r), f1_p=float(f1_of(y, P['ours'][r], NC)), f1_p0=float(f1_of(y, P['ours_p0'][r], NC)))
                   for r in (1, 2, 4)]
            for e in eff: e['diff'] = e['f1_p'] - e['f1_p0']
            out_rows.append(dict(key=f'{key}|pretraining-seed effect (draws 1,2,4)', dataset=ds, K=K, family='outside', items=eff,
                                 mean_abs_diff=float(np.mean([abs(e['diff']) for e in eff]))))
            # ---- 5-draw references
            c5 = boot2.Cell(y, sid, NC, R=5)
            for a, src in (('ours', 'ours_p0'), ('scratch', 'scratch'), ('lgbm', 'lgbm'), ('knn10', 'knn10')): c5.add(a, P[src][:5])
            c5n = boot2.Cell(y, sid, NC, R=5)
            for a in ('ours', 'scratch', 'lgbm', 'knn10'): c5n.add(a, P[a][:5])
            for b in ('lgbm', 'scratch', 'knn10'):
                for nm, cc in (('paper_5draws_p0', c5), ('new_design_draws0-4', c5n)):
                    c = cc.compare('ours', b)
                    OUT['reference_5draw'].append(dict(key=f'{key}|ours-{b}', which=nm, diff=c['diff'], per_draw=c['per_draw'], boot_ci=c['ci'], t=tstat(c['per_draw']), n_pos=c['n_pos']))
            print(f'{key}: {cell.nS} test sessions; ' + ', '.join(f'{a} {obs[a]["mean"]:.2f}' for a in obs), flush=True)

    # ---- R6(b)/(c): Holm within the family
    adj_t = holm([r['t']['p'] for r in fam_rows]); adj_b = holm([r['boot']['p'] for r in fam_rows])
    for r, at, ab in zip(fam_rows, adj_t, adj_b):
        r['t']['p_holm'] = float(at); r['boot']['p_holm'] = float(ab)
        r['boot_ci_excludes_zero'] = bool(r['boot']['ci'][0] > 0 or r['boot']['ci'][1] < 0)
    OUT['family'] = fam_rows; OUT['outside_family'] = out_rows
    # boot2.json agreement of the paper's 5-draw reference
    try:
        b2 = {c['key']: c for c in json.load(open(os.path.join(ROOT, 'results', 'boot2.json')))['comparisons']}
        agree = {}
        for r in OUT['reference_5draw']:
            if r['which'] != 'paper_5draws_p0': continue
            ds, Kk, pair = r['key'].split('|'); k2 = f'fewshot|{ds}|{Kk}|task|{pair}'
            if k2 in b2: agree[r['key']] = bool(abs(b2[k2]['diff'] - r['diff']) < 1e-6 and np.allclose(b2[k2]['ci'], r['boot_ci'], atol=1e-6))
        OUT['checks']['paper_5draw_reproduces_boot2_json'] = agree
    except FileNotFoundError:
        pass
    json.dump(OUT, open(os.path.join(ROOT, 'results', 'draws20_primary.json'), 'w'), indent=1)

    print('\nPRIMARY FAMILY (20 draws, paired t df 19, Holm over 6; sensitivity: two-level bootstrap R=20)')
    for r in fam_rows:
        print(f"{r['family']} {r['key']:28s} diff {r['diff']:+6.2f} (SD {r['sd_draws']:.2f}, {r['n_pos']}/{len(r['per_draw'])} positive) t95 [{r['t']['ci'][0]:+.2f},{r['t']['ci'][1]:+.2f}] "
              f"p {r['t']['p']:.4f} holm {r['t']['p_holm']:.4f} | boot [{r['boot']['ci'][0]:+.2f},{r['boot']['ci'][1]:+.2f}] p {r['boot']['p']:.4f} holm {r['boot']['p_holm']:.4f} "
              f"| by pseed {', '.join(f'{k}:{v:+.2f}' for k, v in r['mean_by_pretraining_seed'].items())}")
    print('\nOUTSIDE THE FAMILY (descriptive, unadjusted)')
    for r in out_rows:
        if 'items' in r:
            print(f"{r['key']}: " + '; '.join(f"d{e['draw']} p{e['pseed']} {e['f1_p']:.2f} vs p0 {e['f1_p0']:.2f} ({e['diff']:+.2f})" for e in r['items'])); continue
        print(f"{r['key']:28s} diff {r['diff']:+6.2f} ({r['n_pos']}/{len(r['per_draw'])} positive) t95 [{r['t']['ci'][0]:+.2f},{r['t']['ci'][1]:+.2f}] p {r['t']['p']:.4f} | boot [{r['boot']['ci'][0]:+.2f},{r['boot']['ci'][1]:+.2f}]")
    print('\n5-DRAW REFERENCE')
    for r in OUT['reference_5draw']:
        print(f"{r['which']:22s} {r['key']:28s} diff {r['diff']:+6.2f} per-draw [{', '.join(f'{x:+.1f}' for x in r['per_draw'])}] boot [{r['boot_ci'][0]:+.2f},{r['boot_ci'][1]:+.2f}] t95 [{r['t']['ci'][0]:+.2f},{r['t']['ci'][1]:+.2f}] p {r['t']['p']:.4f}")
    print('\nOBSERVERS (mean, SD, min-max over 20 draws)')
    for k, c in OUT['cells'].items():
        print(k, ' | '.join(f"{a} {o['mean']:.2f} (SD {o['sd']:.2f}, {o['min']:.1f}-{o['max']:.1f})" for a, o in c['observers'].items()))
    print('checks', json.dumps(OUT['checks']))
    print('written results/draws20_primary.json')


if __name__ == '__main__':
    main()
